import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { config } from '../config.js';
import { frontmatter } from './notes.js';
import { listTasks, type TaskNote } from './tasks.js';

// Board.md is app-generated on every task change — a checkpoint projection of
// task state into plain markdown. No Dataview/Bases plugin required. It is
// app-owned: full rewrite each time, and users are told not to edit it.

const STATUS_ICON: Record<string, string> = {
  todo: '⬜',
  dispatched: '📤',
  running: '🔄',
  review: '👀',
  done: '✅',
  failed: '❌',
};

function row(task: TaskNote): string {
  const icon = STATUS_ICON[task.status] ?? '❔';
  const title = task.title.replace(/\|/g, '/');
  const run = task.run ? `[[${task.run}]]` : '—';
  const created = task.created ? task.created.slice(0, 10) : '—';
  return `| [[${task.slug}\\|${title}]] | ${icon} ${task.status} | ${run} | ${created} |`;
}

export function renderBoard() {
  const tasks = listTasks().sort((a, b) => (b.created ?? '').localeCompare(a.created ?? ''));
  const projects = [...new Set(tasks.map((t) => t.project ?? 'unassigned'))].sort();

  const lines: string[] = [
    frontmatter({ type: 'board', generated: new Date().toISOString() }),
    '# Task Board',
    '',
    '_Generated by Jarvis on every task change — edits here will be overwritten._',
    '',
  ];

  if (!tasks.length) lines.push('No tasks yet.');

  for (const project of projects) {
    const own = tasks.filter((t) => (t.project ?? 'unassigned') === project);
    const done = own.filter((t) => t.status === 'done').length;
    lines.push(`## ${project} — ${done}/${own.length} done`, '');
    lines.push('| Task | Status | Run | Created |');
    lines.push('| --- | --- | --- | --- |');
    for (const task of own) lines.push(row(task));
    lines.push('');
  }

  writeFileSync(join(config.vaultPath, 'Board.md'), lines.join('\n'));
}
